run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1

linters:
  enable:
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - noctx
    - gosec
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - misspell

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-merge-base: origin/main
